parameters:
    templates_dir: "templates"

twig:
    default_path: '%kernel.project_dir%/%templates_dir%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
